---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "go-app-config-iz7c"
  namespace: "default"
  labels:
    app: "go-app"
data:
  PORT: "8080"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "go-app"
  namespace: "default"
  labels:
    app: "go-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "go-app"
  template:
    metadata:
      labels:
        app: "go-app"
    spec:
      containers:
      - name: "go-app-sha256-1"
        image: "gcr.io/projeto-eng1/go.app:latest"
        env:
        - name: "PORT"
          valueFrom:
            configMapKeyRef:
              key: "PORT"
              name: "go-app-config-iz7c"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "go-app-hpa-1clw"
  namespace: "default"
  labels:
    app: "go-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "go-app"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 85
